### ISSUE TITLE
Not able to sync Gradle properly.

### ISSUE THREAD

**Issue by jet0499** [Nehaadnekar/File-Sharing-App-MINI-PROJECT#1]
<img width="1678" alt="gradle sync error" src="https://user-images.githubusercontent.com/55457638/96373508-8b96b180-118a-11eb-805c-f5965f1bedbc.png">

Problem - Gradle sync failed is a common issue faced during the Gradle setup.
Solution - Click on offline Gradle sync and keep your internet connection stable.

**Comment by prachi1234bansal** [comment]
![Screenshot (133)](https://user-images.githubusercontent.com/52649082/96475332-bf082900-11e8-11eb-93f4-6cc8261fc9d3.png)
